[project]
name = "py-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcadepy>=1.10.0",
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "python-dotenv>=1.2.1",
]
