[project]
name = "python-openai-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agents-arcade>=0.0.4",
    "openai-agents>=0.6.1",
    "python-dotenv>=1.2.1",
]
